trigger:
  branches:
    include:
      - master
  tags:
    include:
      - '*'

resources:
  containers:
  - container: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: curl -s -f http://localhost:9200/_cat/health >/dev/null || exit 1
      interval: 10s
      timeout: 10s
      retries: 120
  - container: python
    context: .

