version: '3'

volumes:
  elasticsearch-single-data: {}

services:
  elasticsearch-single:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: elasticsearch-single
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-single-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
  
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.16.2
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch-single:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch-single
